generator: admingenerator.generator.doctrine
params:
    model: AppBundle\Entity\Code
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AppBundle
    pk_requirement: ~
    fields:
        name:
            label: Имя
        createdAt:
            label: Создан
        updatedAt:
            label: Обновлен
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Коды материалов
            display: [name, createdAt, updatedAt]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
            filters: [name]
            filtersMode: top
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: Новый код материала
            display: [name]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Вы редактируете код материала \"%object%\"|{ %object%: Code.name }|"
            display: [name]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Вы просматриваете код материала \"%object%\"|{ %object%: Code.name }|"
            display: [name, createdAt, updatedAt]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
