generator: admingenerator.generator.doctrine
params:
    model: AppBundle\Entity\Consumption
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AppBundle
    pk_requirement: ~
    fields:
        material:
            label: Наименование материала
        group:
            label: Группа ЗИП
        quantity:
            label: Количество
        date:
            label: Дата
            formType: Admingenerator\FormExtensionsBundle\Form\Type\DatePickerType 
        description:
            label: Описание
        createdAt:
            label: Создан
        updatedAt:
            label: Обновлен
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Расход материалов
            display: [material, group, quantity, date, description, createdAt, updatedAt]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: Новый расход
            display: [material,group, quantity, date, description]
            actions:
                save: ~
                list: ~
            fields: 
                description:   
                    addFormOptions:
                        required: false
    edit:
        params:
            title: "Вы редактируете расход для \"%object%\"|{ %object%: Consumption.material }|"
            display: [material,group, quantity, date, description]
            actions:
                save: ~
                list: ~
            fields: 
                description:   
                    addFormOptions:
                        required: false
    show:
        params:
            title: "Вы просматриваете расход для \"%object%\"|{ %object%: Consumption.material }|"
            display: [material, group, quantity, date, description, createdAt, updatedAt]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
