generator: admingenerator.generator.doctrine
params:
    model: AppBundle\Entity\Inventory
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AppBundle
    pk_requirement: ~
    fields:
        material:
            label: Наименование материала
        date:
            label: Дата
        before:
            label: До
        after:
            label: После
        createdAt:
            label: Создан
        updatedAt:
            label: Обновлен
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Инвентаризация
            display: [material, date, before, after, createdAt, updatedAt]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: Новая проверка
            display: [material, date, before, after]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Вы редактируете \"%object%\"|{ %object%: Inventory.material }|"
            display: [material, date, before, after]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Вы просматриваете \"%object%\"|{ %object%: Inventory.material }|"
            display: [material, date, before, after, createdAt, updatedAt]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
