generator: admingenerator.generator.doctrine
params:
    model: AppBundle\Entity\Material
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AppBundle
    pk_requirement: ~
    fields:
        name:
            label: Имя
        code:
            label: Код ЗИП
        createdAt:
            label: Создан
        updatedAt:
            label: Обновлен
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Материалы
            display: [name, code, createdAt, updatedAt]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
            filters: [name, code]
            filtersMode: top
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: Новый материал
            display: [name, code]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Вы редактируете материал  \"%object%\"|{ %object%: Material.name }|"
            display: [name, code]
            actions:
                save: ~
                list: ~
            fields: 
                code:   
                    addFormOptions:
                        required: true
    show:
        params:
            title: "Вы просматриваете материал \"%object%\"|{ %object%: Material.name }|"
            display: [name, code, createdAt, updatedAt]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
