app_bundle:
    resource: "@AppBundle/Controller/Inventory"
    type:     annotation
    prefix:   /admin/app_bundle/Inventory

AppBundle_admin_app_bundle_Consumption:
    resource: "@AppBundle/Controller/Consumption/"
    type:     admingenerator
    prefix:   /admin/app_bundle/Consumption

AppBundle_admin_app_bundle_Inventory:
    resource: "@AppBundle/Controller/Inventory/"
    type:     admingenerator
    prefix:   /admin/app_bundle/Inventory

AppBundle_admin_app_bundle_Receipt:
    resource: "@AppBundle/Controller/Receipt/"
    type:     admingenerator
    prefix:   /admin/app_bundle/Receipt

AppBundle_admin_app_bundle_Material:
    resource: "@AppBundle/Controller/Material/"
    type:     admingenerator
    prefix:   /

AppBundle_admin_app_bundle_Code:
    resource: "@AppBundle/Controller/Code/"
    type:     admingenerator
    prefix:   /admin/app_bundle/Code

AppBundle_admin_app_bundle_Group:
    resource: "@AppBundle/Controller/Group/"
    type:     admingenerator
    prefix:   /admin/app_bundle/Group
    
